on: [push]

jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        ruby: [ '2.5', '2.6', '2.7' ]
    name: ynar ruby:${{matrix.ruby}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          cp config.yaml.example config.yaml
          bundle exec rspec
